apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghproxy
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vagrant/ghproxystore"
