# Plugin configuration
---
triggers:
- repos:
  - iriver9702
  join_org_url: "https://git.k8s.io/community/community-membership.md#member"
  only_org_members: true

owners:
  mdyamlrepos:
  - iriver9702/readygo
  - iriver9702/kubernetes
  skip_collaborators:
  - iriver9702/kubernetes
  - iriver9702/readygo

# TODO(fejta): delete these in before April
use_deprecated_2018_implicit_self_approve_default_migrate_before_july_2019: true
use_deprecated_2018_review_acts_as_approve_default_migrate_before_july_2019: true

approve:
- repos:
  - iriver9702/kubernetes
  - iriver9702/readygo
  require_self_approval: false
  lgtm_acts_as_approve: true
  ignore_review_state: false

# Lower bounds in number of lines changed; XS is assumed to be zero.
size:
  s:   10
  m:   30
  l:   100
  xl:  500
  xxl: 1000

label:
  additional_labels:
    # This label is used by the API review process
    # https://git.k8s.io/community/sig-architecture/api-review-process.md#mechanics
    - api-review
    # These labels are used by Kubeflow
    # TODO(https://github.com/kubernetes/test-infra/issues/8648): Switch
    # to configuring prefixes and not individual labels once  that's supported.
    - community/discussion
    - community/maintenance
    - community/question
    - cuj/build-train-deploy
    - cuj/multi-user
    - platform/aws
    - platform/azure
    - platform/gcp
    - platform/minikube
    - platform/other
    - tide/merge-method-merge
    - tide/merge-method-rebase
    - tide/merge-method-squash

lgtm:
- repos:
  - iriver9702/kubernetes
  - iriver9702/readygo
  review_acts_as_lgtm: true

blockades:
- repos:
  - iriver9702/kubernetes
  blockregexps:
  - ^examples/
  explanation: "examples/ has moved to https://github.com/kubernetes/examples/"
- repos:
  - iriver9702/readygo
  blockregexps:
  - ^events/elections/2019
  explanation: "These files are historical, and from events that have already occurred."

blunderbuss:
  max_request_count: 2
  use_status_availability: true

cat:
  key_path: /etc/cat-api/api-key

goose:
  key_path: /etc/unsplash-api/honk.txt

heart:
  adorees:
  - mirandachrist
  commentregexp: ".*"

slack:
  mergewarnings:
  - repos:
    - iriver9702/kubernetes
    channels:
    - kubernetes-dev
    exempt_users:
    - k8s-ci-robot # future home of tide
    exempt_branches:
        release-1.19:
            - cpanato # Branch Manager
            - dougm # Patch Release Team
            - feiskyer # Patch Release Team
            - hasheddan # Branch Manager
            - hoegaarden # Patch Release Team
            - idealhack # Patch Release Team
            - justaugustus # Patch Release Team
            - saschagrunert # Branch Manager
            - tpepper # Patch Release Team
        feature-serverside-apply:
            - lavalamp # feature-serverside-apply "branch manager"
            - apelisse # feature-serverside-apply "branch manager"
        feature-rate-limiting:
            - lavalamp # feature-rate-limiting "branch manager"
            - deads2k # feature-rate-limiting "branch manager"
  - repos:
    - iriver9702/test-infra
    channels:
    - testing-ops
    exempt_users:
    - k8s-ci-robot


milestone_applier:
  iriver9702/kubernetes:
    master: v1.20
    release-1.19: v1.19
  iriver9702/readygo:
    master: v1.0

repo_milestone:
  # Default maintainer
  '':
    # You can curl the following endpoint in order to determine the github ID of your team
    # responsible for maintaining the milestones. You may need to specify the page number.
    # curl -H "Authorization: token <token>" "https://api.github.com/orgs/<org-name>/teams?page=N"
    maintainers_id: 4110120
    maintainers_team: members
  iriver9702/readygo:
    maintainers_id: 4110120
    maintainers_team: members
    maintainers_friendly_name:  Readygo Repo Maintainers
  

project_config:
  project_org_configs:
    iriver9702:
      org_maintainers_team_id: 4110120 # sig-testing-dummy-project-team
      org_default_column_map:
        test-infra-dummy-testing-project-plugin:
          To do
        KEP Implementation Tracking:
          To do
      project_repo_configs:
        kubernetes:
          repo_maintainers_team_id: 4110120 # milestone-maintainers
          repo_default_column_map:
            component-base:
              To do
            Workloads:
              Backlog
        readygo:
          repo_maintainers_team_id: 4110120 # 
          repo_default_column_map:
            component-base:
              To do
            Doc Writing and Editing:
              To do

config_updater:
  maps:
    label_sync/labels.yaml:
      name: label-config
      clusters:
        kubernetes:
          - test-pods
    config/prow/config.yaml:
      name: config
    config/prow/plugins.yaml:
      name: plugins
    config/jobs/**/*.yaml:
      name: job-config
      gzip: true
    experiment/test-configmap.txt:
      name: test-configmap
      gzip: true

welcome:
- repos:
  - iriver9702/readygo
  - iriver9702/kubernetes
  message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> 🎉.  :smiley:"

require_matching_label:
- missing_label: needs-kind
  org: iriver9702
  repo: readygo
  prs: true
  regexp: ^kind/
- missing_label: needs-sig
  org: iriver9702
  repo: readygo
  prs: true
  regexp: ^(sig|wg|committee)/
  # Define needs-sig separately for issues so that we only comment on issues.
- missing_label: needs-sig
  org: iriver9702
  repo: readygo
  issues: true
  regexp: ^(sig|wg|committee)/
  missing_comment: |
    There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
    - `/sig <group-name>`
    - `/wg <group-name>`
    - `/committee <group-name>`

    Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.
- missing_label: needs-priority
  org: iriver9702
  repo: readygo
  prs: true
  regexp: ^priority/
- missing_label: needs-kind
  org: iriver9702
  repo: readygo
  prs: true
  issues: true
  regexp: ^kind/

retitle:
  allow_closed_issues: true

cherry_pick_unapproved:
  comment: |
    This cherry pick PR is for a release branch and has not yet been approved by [Release Managers](https://git.k8s.io/sig-release/release-managers.md).
    Adding the `do-not-merge/cherry-pick-not-approved` label.

    To merge this cherry pick, it must first be approved (`/lgtm` + `/approve`) by the relevant OWNERS.

    **AFTER** it has been approved by code owners, please ping the **kubernetes/release-managers** team in a comment to request a cherry pick review.

    (For details on the patch release process and schedule, see the [Patch Releases](https://git.k8s.io/sig-release/releases/patch-releases.md) page.)

# Enabled plugins per repo.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
plugins:
  # Enable the following for any bazelbuild repo (rules_k8s, rules_docker) that sends prow webhooks
  # Repos that do not send prow webhooks will see no effect.
  iriver9702:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - golint
  - goose
  - heart
  - help
  - hold
  - invalidcommitmsg
  - label
  - lgtm
  - lifecycle
  - owners-label
  - pony
  - retitle
  - shrug
  - sigmention
  - size
  - skip
  - slackevents
  - trigger
  - verify-owners
  - welcome
  - wip
  - yuks


  iriver9702/kubernetes:
  - blockade
  - cherry-pick-unapproved
  - mergecommitblocker
  - milestone
  - milestoneapplier
  - milestonestatus
  - override
  - release-note
  - require-matching-label

external_plugins:
  iriver9702:
  # - name: refresh-remote
  #   endpoint: https://prow.cloudminds.com:31008/
  #   events:
  #   - issue_comment
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request