presubmits:
  zhanghe9702/readygo:
  - name: pull-readygo-go-build
    always_run: true
    decorate: true
    path_alias: zhanghe9702/readygo
    spec:
      containers:
      - image: golang:1.14.4
        env:
        - name: GO111MODULE
          value: "on"
        command:
        - go
        args:
        - build
        - ./...
